### ISSUE TITLE
Infra: Improvements for insfrastructure

### ISSUE THREAD

**Issue by petertrr** [cqfn/save-cloud#40]
* junit5 extensions instead of base classes for tests using dynamic properties: https://www.baeldung.com/spring-dynamicpropertysource#an-alternative-test-fixtures
* Add docker volume for grafana configs, store them in `save-deploy`. Configure grafana to work behind nginx
* For services that do not need replication (orchestrator (?), prometheus and grafana) add the following to compose file:
  ```yaml
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"
     ```
